#version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metabase_db
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - metabase-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase_user -d metabase_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - metabase-net
    restart: unless-stopped

networks:
  metabase-net:
    driver: bridge

volumes:
  postgres-data:
